[Feat] profile edit 컴포넌트 구현
K-BigAnt/Front pull request #29
Opened 2024-10-14 11:15 UTC by Arkingco

## 관련 문서

## 연관된 이슈

- #27 

## 작업 내용
- 프로필 컴포넌트 구현 및 적용

### 스크린샷

## 추가 리뷰 요구사항

-

2024-11-04 10:23 UTC, lamPolar reviewed
이번 풀리퀘에서 component/profile/Edit.tsx만 변경하신 거 맞을까요?

2024-11-04 10:25 UTC, Arkingco commented
![image](https://github.com/user-attachments/assets/4516995e-1b3c-497a-9402-ae4b2a44f31b)
이 두 파일 변경 하였습니다!

2024-11-15 04:53 UTC, lamPolar requested changes

2024-11-15 04:53 UTC, lamPolar commented on src/app/profile/[name]/page.tsx
> +				<div className="flex flex-row items-cen	ter justify-center h-[200px]">
center 사이에 띄어쓰기 오타나신것 같습니다.

2024-11-15 04:53 UTC, lamPolar commented on src/app/profile/[name]/page.tsx
> +'use client';
혹시 이 파일에서 use client 선언하신 이유가 있으실까요?
내부에서 useState, useEffect같은 훅이나 window의 접근이 없어보여서요.
어떤 점때문에 선언하신 건지 궁금합니다

2024-11-16 04:30 UTC, Arkingco commented on src/app/profile/[name]/page.tsx
> +				<div className="flex flex-row items-cen	ter justify-center h-[200px]">
오타 확인 감사합니다

2024-11-16 04:33 UTC, Arkingco commented on src/app/profile/[name]/page.tsx
> +'use client';
useState를 사용 하려고 추가 했다가 이후 코드에서 state를 삭제했는데 그 때 만들어둔 use client가 추가 된 것 같습니다
수정 하겠습니다

2024-11-18 13:44 UTC, lamPolar approved these changes

2024-11-18 14:09 UTC, merged